# add comment
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: kaizheh/nginx 
    securityContext:
      privileged: false
      readOnlyRootFilesystem: true 
