# add comment
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  hostNetwork: false
  hostIPC: false
  hostPID: false
  containers:
  - name: nginx
    image: kaizheh/nginx 
    securityContext:
      privileged: false
      readOnlyRootFilesystem: true 
      runAsUser: 100
      runAsGroup: 1000
    volumeMounts:
    - name: tmp
      mountPath: /var/tmp
  volumes:
  - name: tmp
    hostPath:
      path: /tmp
      type: Directory
